---
name: Myo Minn
surname: Oo
position: "Post-doctoral Fellow"
address: "Department of Medical Microbiology and Infectious Diseases, University of Manitoba, Winnipeg, Canada"
phone: +1 204 557 9337
profilepic: "./img/myominnoo.jpg"
www: myominnoo.github.io
email: "dr.myominnoo@gmail.com"
github: myominnoo
linkedin: myominnoo
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Myo is an epidemiologist with a medical background, specializing in global health and implementation research to better comprehend infectious diseases among vulnerable populations. Since 2016, I have published 30+ peer-reviewed papers in the fields of infectious disease epidemiology, with a focus on TB, HIV, and malaria in developing countries including Myanmar, Thailand, Bhutan, Nepal, and China. I also serve as an academic editor for PLoS ONE and as an associate editor for Public Health Challenges Journal (Wiley) while also participating as a scientific reviewer for several scientific journals. My current interests revolve around understanding infectious disease epidemiology, diseaes burdens, and transmission dynamics among vulnerable populations, not limited to migrants, sex workers, and gbMSM."
docname: Resume
output: 
  vitae::twentyseconds:
    keep_tex: false
always_allow_html: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Positions

```{r}
readxl::read_excel("data/data.xlsx", sheet	= "positions") %>% 
  detailed_entries(what, when, with, where)
```

# Education

```{r}
readxl::read_excel("data/data.xlsx", sheet	= "education") %>% 
  detailed_entries(what, when, with)
```

# Grants, Awards, & Honors

```{r}
readxl::read_excel("data/data.xlsx", sheet	= "grants") %>% 
  detailed_entries(what, when, with)
```

# Academic Contributions & Mentorship

```{r}
readxl::read_excel("data/data.xlsx", sheet	= "affiliations") %>% 
  detailed_entries(what, when, with)
```

# Skills

```{r}
readxl::read_excel("data/data.xlsx", sheet	= "skills") %>% 
	dplyr::summarise(what = paste(what, collapse = ", ")) %>% 
	detailed_entries(what)
```

# Research themes

```{r}
readxl::read_excel("data/data.xlsx", sheet	= "themes") %>% 
	dplyr::summarise(what = paste(what, collapse = ", ")) %>% 
	detailed_entries(what)
```


This document is written in rmarkdown using the package `vitae` and the theme `twentyseconds`. See source codes \href{https://github.com/myominnoo/cv}{here}.



